# -*- coding: utf-8 -*-
"""SE ver 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSlEYw4D91pZ_phv-9v00_w9ic5yjG_0
"""

with open('/content/data.txt', 'r') as file:
    a = float(file.readline())
    b = float(file.readline())
    c = float(file.readline())
    x = float(file.readline())
y = a * x * x + b * x + c
print('The value of y is:', y)