# -*- coding: utf-8 -*-
"""SE Ver 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTmKk6KIIgcmoPhcg2EoB4Yg7ry7Wzv6
"""

a=float(input('Enter the value of a: '))
b=float(input('Enter the value of b: '))
c=float(input('Enter the value of c: '))
x=float(input('Enter the value of x: '))
y=a*x*x+b*x+c
print('The value of y is ',y)